version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    image: traefikturkey/ontology
    hostname: ontology
    container_name: ontology
    stdin_open: true
    tty: true 
    environment:
      DOTFILES_URL: ${DOTFILES_URL:-https://github.com/traefikturkey/dotfiles.git}
      DOTFILES_OVERRIDE_URL: ${DOTFILES_OVERRIDE_URL}
    secrets:
      - user_ssh_key
    volumes:
      - ../:/app:cached 
secrets:
  user_ssh_key:
    file: ~/.ssh/id_ed25519