version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${USER:-anvil}
        - TERM_SHELL=${TERM_SHELL:-zsh}
    image: traefikturkey/ontology
    hostname: ontology
    container_name: ontology
    stdin_open: true
    tty: true 
    environment:
      DOTFILES_URL: ${DOTFILES_URL:-https://github.com/traefikturkey/dotfiles.git}
      TERM_SHELL: ${TERM_SHELL:-zsh}
      TZ: ${TZ:-America/New_York}
    secrets:
      - user_ssh_key
    volumes:
      - ../:/app 
      - shell-history:/mnt/.devcontainer
      - dotfiles:/home/${USER:-anvil}/.dotfiles

volumes:
  shell-history:
  dotfiles:

secrets:
  user_ssh_key:
    file: ~/.ssh/id_ed25519