version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true 
    secrets:
      - user_ssh_key
    volumes:
      - ../:/app:cached 
secrets:
  user_ssh_key:
    file: ~/.ssh/id_ed25519