---
- name: Create Symlink to ~/.dotfiles
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone Dotfiles Repository
      git:
        repo: "{{ lookup('env', 'DOTFILES_URL') }}"
        dest: "{{ lookup('env', 'HOME') + '/.dotfiles' }}"
        recursive: yes  # Recursively clone submodules
        update: yes
        accept_hostkey: yes

    - name: Execute ~/.dotfiles/install
      command: "~/.dotfiles/install"

    - name: Check if .dotfiles symlink exists
      stat:
        path: "{{ lookup('env', 'PWD') + '/.dotfiles' }}"
      register: dotfiles_symlink

    - name: Delete .dotfiles symlink
      file:
        path: "{{ lookup('env', 'PWD') + '/.dotfiles' }}"
        state: absent
      when: dotfiles_symlink.stat.islnk | default(false)

    - name: Create Symlink
      file:
        src: "{{ lookup('env', 'HOME') + '/.dotfiles' }}"
        dest: "{{ lookup('env', 'PWD') + '/.dotfiles' }}"
        state: link
